% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Nov-2021 00:18:02
%  MATLAB version: 9.5.0.1586782 (R2018b) Update 8
% -------------------------------------------------------------------
saveVarsMat = load('Tablescript_Varibles_Names_1_all_time_threshold.mat');

Tbl_VEI_allcat = saveVarsMat.Tbl_VEI_allcat; % <1x1 table> unsupported class

Tbl_VEI_cat = saveVarsMat.Tbl_VEI_cat; % <1x1 table> unsupported class

Tbl_VEI_dom = saveVarsMat.Tbl_VEI_dom; % <1x1 table> unsupported class

Tbl_VEI_ed = saveVarsMat.Tbl_VEI_ed; % <1x1 table> unsupported class

Tbl_VEI_etd = saveVarsMat.Tbl_VEI_etd; % <1x1 table> unsupported class

Tbl_VEI_morph = saveVarsMat.Tbl_VEI_morph; % <1x1 table> unsupported class

Tbl_VEI_num = saveVarsMat.Tbl_VEI_num; % <1x1 table> unsupported class

Tbl_VEI_tec = saveVarsMat.Tbl_VEI_tec; % <1x1 table> unsupported class

Tbl_unhistVEI_cat = saveVarsMat.Tbl_unhistVEI_cat; % <1x1 table> unsupported class

Tbl_unhistVEI_dom = saveVarsMat.Tbl_unhistVEI_dom; % <1x1 table> unsupported class

Tbl_unhistVEI_morph = saveVarsMat.Tbl_unhistVEI_morph; % <1x1 table> unsupported class

Tbl_unhistVEI_tec = saveVarsMat.Tbl_unhistVEI_tec; % <1x1 table> unsupported class

bol_diff = saveVarsMat.bol_diff; % <1x1 string> unsupported class

eruption_data = saveVarsMat.eruption_data; % <1x1 table> unsupported class

eruption_data_clean = saveVarsMat.eruption_data_clean; % <1x1 table> unsupported class

eruption_data_clean_ind = saveVarsMat.eruption_data_clean_ind; % <7252x1 double> too many elements

eruption_data_clean_nan = saveVarsMat.eruption_data_clean_nan; % <1x1 table> unsupported class

eruption_data_complete = saveVarsMat.eruption_data_complete; % <1x1 table> unsupported class

eruption_data_time = -10450;

iVEI = 1;

i_bol = 0;

itime = 1;

master_direct = '/Users/lukecolosi/Desktop/VEI_Forecasting-main';

time_thresh = saveVarsMat.time_thresh; % <1x1 string> unsupported class

volcano_data = saveVarsMat.volcano_data; % <1x1 table> unsupported class

clear saveVarsMat;
